# Generated by Django 3.2.7 on 2021-12-08 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0004_alter_mytask_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytask',
            options={'ordering': ['complete']},
        ),
        migrations.AlterField(
            model_name='mytask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
